### ISSUE TITLE
Got a 401 unauthorized error 

### ISSUE THREAD

**Issue by vikyding** [microsoftgraph/console-java-connect-sample#1]
Got a 401 Unauthorized Error when requested Graph API. When I pasted the authorization code into the console, it got a 401 error show as below:

401
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure.",
    "innerError": {
      "request-id": "be979fa7-653b-4bf4-9640-47fc8aa3fcba",
      "date": "2018-08-03T17:43:32"
    }
  }
}
I have decoded the accessToken, it seems everything are right except resource. In decoded Token, it showed  "aud": "https://graph.windows.net". In MicrosoftAzureActiveDirectoryApi in com.github.scribejava.apis apk, it used an old ms graph URL as resource.

**Comment by MingGeoswift** [comment]
I have the same problem. Can anyone help please? thanks

**Comment by isoubelet** [comment]
Hi @vikyding 
I am having the same issue - did you manage to fix it?

Thanks

**Comment by Xargas** [comment]
Same here. The Web-Token is ok, but the request "makeAuthenticatedMeRequest" fails with 401
Granting rights in the Azure application as mentioned for older application is also not solving this response.

Is the sample code outdated? Or is something just missing in the README.md?

**Comment by jasonjoh** [comment]
Give this a try with the latest code, I suspect those changes should resolve these problems.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-java for a Java sample.
