### ISSUE TITLE
Not able to convert this project to maven

### ISSUE THREAD

**Issue by freelancer6969** [microsoftgraph/console-java-connect-sample#7]
Hello,

I am working on Microsoft Graph API implementation for sending an email.

I want to integrate this feature into the existing maven project.

I try to convert this project into the maven project,

For this, I have tried the steps mentioned at [https://dzone.com/articles/how-to-convert-maven-to-gradle-and-vice-versa](url)

I am able to generate pom.xml. But while running it I am facing multiple build failures.

Can you please let me know if the same sample is available as a maven configuration. 

or if there is an alternative to run this project as a maven project

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-java for a Java sample.
