### ISSUE TITLE
Not able to get authorization code

### ISSUE THREAD

**Issue by nikita591** [microsoftgraph/console-java-connect-sample#8]
I ran the code , build is successful. 
I made few changes in the code ,
1. First , I replace the CLIENT_ID value as my application client id's 
2. Secondly also change the redirect url in Constants.java.
3. Also one more change which i made is in MicrosoftAzureAD20Api.java , I replaced the 
    getAccessTokenEndpoint() and getAuthorizationBaseUrl() URL's as per my application.
After running the code , it ran without error , I printed the authorization URL in console as well, but I am not getting authorization code in URL(which I printed in console).

Note: As per the steps explained in this repo, I should get authorization code in URL.

Please help me out.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-java for a Java sample.
